language: scala
scala:
    - "2.11.4"
jdk:
    - oraclejdk8
sudo: false

before_install:
    - curl -0 https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip -o consul.zip && unzip consul.zip && nohup ./consul agent -dev &

